// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: WeatheratorCrow

#ifndef _WEATHERATORCROW_UI_H
#define _WEATHERATORCROW_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen(lv_event_t * e);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Temp1;
extern lv_obj_t * ui_Hum1;
extern lv_obj_t * ui_Batt1;
extern lv_obj_t * ui_Upd1;
extern lv_obj_t * ui_Wifi1;
extern lv_obj_t * ui_Desc1;
extern lv_obj_t * ui_Status1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Temp2;
extern lv_obj_t * ui_Hum2;
extern lv_obj_t * ui_Batt2;
extern lv_obj_t * ui_Upd2;
extern lv_obj_t * ui_Wifi2;
extern lv_obj_t * ui_Desc2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Temp3;
extern lv_obj_t * ui_Hum3;
extern lv_obj_t * ui_Batt3;
extern lv_obj_t * ui_Upd3;
extern lv_obj_t * ui_Wifi3;
extern lv_obj_t * ui_Desc3;
extern lv_obj_t * ui_TSStatus;
// SCREEN: ui_PressureScreen
void ui_PressureScreen_screen_init(void);
void ui_event_PressureScreen(lv_event_t * e);
extern lv_obj_t * ui_PressureScreen;
extern lv_obj_t * ui_PressureChart;
extern lv_obj_t * ui_Pres1;
extern lv_obj_t * ui_TickLabel6hr;
extern lv_obj_t * ui_TickLabel12hr;
extern lv_obj_t * ui_TickLabel18hr;
extern lv_obj_t * ui_TickLabelNow;
extern lv_obj_t * ui_TickLabel3hr;
extern lv_obj_t * ui_TickLabel9hr3;
extern lv_obj_t * ui_TickLabel15hr;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_bluehexbg_png);    // assets/BlueHexBG.png



LV_FONT_DECLARE(ui_font_MontserratMedium60);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
